/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlueprintsRouteImport } from './routes/blueprints'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WordpressRouteImport } from './routes/wordpress'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiValidationHealthRouteImport } from './routes/api/validationHealth'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintsRoute = BlueprintsRouteImport.update({
  id: '/blueprints',
  path: '/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WordpressRoute = WordpressRouteImport.update({
  id: '/wordpress',
  path: '/wordpress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidationHealthRoute = ApiValidationHealthRouteImport.update({
  id: '/api/validationHealth',
  path: '/api/validationHealth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/launch': typeof LaunchRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/wordpress': typeof WordpressRoute
  '/api/health': typeof ApiHealthRoute
  '/api/validationHealth': typeof ApiValidationHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/launch': typeof LaunchRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/wordpress': typeof WordpressRoute
  '/api/health': typeof ApiHealthRoute
  '/api/validationHealth': typeof ApiValidationHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blueprints': typeof BlueprintsRoute
  '/launch': typeof LaunchRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/studio': typeof StudioRoute
  '/wordpress': typeof WordpressRoute
  '/api/health': typeof ApiHealthRoute
  '/api/validationHealth': typeof ApiValidationHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blueprints'
    | '/launch'
    | '/prompts'
    | '/settings'
    | '/studio'
    | '/wordpress'
    | '/api/health'
    | '/api/validationHealth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blueprints'
    | '/launch'
    | '/prompts'
    | '/settings'
    | '/studio'
    | '/wordpress'
    | '/api/health'
    | '/api/validationHealth'
  id:
    | '__root__'
    | '/'
    | '/blueprints'
    | '/launch'
    | '/prompts'
    | '/settings'
    | '/studio'
    | '/wordpress'
    | '/api/health'
    | '/api/validationHealth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlueprintsRoute: typeof BlueprintsRoute
  LaunchRoute: typeof LaunchRoute
  PromptsRoute: typeof PromptsRoute
  SettingsRoute: typeof SettingsRoute
  StudioRoute: typeof StudioRoute
  WordpressRoute: typeof WordpressRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiValidationHealthRoute: typeof ApiValidationHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprints': {
      id: '/blueprints'
      path: '/blueprints'
      fullPath: '/blueprints'
      preLoaderRoute: typeof BlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordpress': {
      id: '/wordpress'
      path: '/wordpress'
      fullPath: '/wordpress'
      preLoaderRoute: typeof WordpressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validationHealth': {
      id: '/api/validationHealth'
      path: '/api/validationHealth'
      fullPath: '/api/validationHealth'
      preLoaderRoute: typeof ApiValidationHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlueprintsRoute: BlueprintsRoute,
  LaunchRoute: LaunchRoute,
  PromptsRoute: PromptsRoute,
  SettingsRoute: SettingsRoute,
  StudioRoute: StudioRoute,
  WordpressRoute: WordpressRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiValidationHealthRoute: ApiValidationHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
